# Generated by Django 5.1.6 on 2025-03-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='Food_cart',
            new_name='Food_cat',
        ),
    ]
