# Generated by Django 5.1.6 on 2025-03-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_img',
            field=models.URLField(default='https://www.primaverakitchen.com/wp-content/uploads/2019/02/Easy-Vegetarian-Meal-Prep-Bowls-Primavera-Kitchen-3-1024x1536.jpg'),
        ),
    ]
