# Generated by Django 5.1.6 on 2025-03-23 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0007_restaurants_remove_menu_menu_img_alter_menu_res_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Res_name', models.CharField(max_length=100)),
                ('Food_cat', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('img', models.URLField(default='https://t3.ftcdn.net/jpg/03/24/73/92/360_F_324739203_keeq8udvv0P2h1MLYJ0GLSlTBagoXS48.jpg')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_img',
            field=models.URLField(default='https://www.primaverakitchen.com/wp-content/uploads/2019/02/Easy-Vegetarian-Meal-Prep-Bowls-Primavera-Kitchen-3-1024x1536.jpg'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='res',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
    ]
