# Generated by Django 5.1.6 on 2025-03-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_restaurant_menu_menu_img_alter_menu_res_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurant',
            new_name='Restaurants',
        ),
    ]
